//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591 

namespace CF.MusicLibrary.Dal
{
    using System;
    using System.Collections.Generic;
    
    [System.CodeDom.Compiler.GeneratedCode("TextTemplatingFileGenerator", "")] 
    public partial class Playback
    {
        public int Id { get; set; }
        public int SongId { get; set; }
        public System.DateTime PlaybackTime { get; set; }
    
        public virtual Song Song { get; set; }
    }
}

#pragma warning restore 1591
